data:
  train_path: "data/raw/main"
  val_path: "data/raw/val"
  annotations_path: "data/annotations/instances_default.json"
  val_annotations_path: "data/annotations/instances_val.json"
  processed_path: "data/processed"

model:
  name: "deeplabv3_resnet101"
  num_classes: 11
  pretrained: true
  use_hybrid: true
  roboflow:
    api_key: "BATlZ8b1AQuon0tnMKIm"
    enhance_water_surface: true

    use_during_training: false  # Recommended false to limit API calls
    use_during_validation: true  # Good to enable for validation to see effect

training:
  batch_size: 4
  epochs: 50
  learning_rate: 0.001
  device: "cpu"
  optimizer: "adam"
  lr_scheduler: true

  # Optional resume from checkpoint
  resume_from_checkpoint: ""

metrics:
  water_thresholds: [0.2, 0.4, 0.6, 0.8]
  silt_thresholds: [0.2, 0.4, 0.6, 0.8]
  debris_thresholds: [0.2, 0.4, 0.6, 0.8]